### ISSUE TITLE
merge will ignore Node-copyfrom...

### ISSUE THREAD

**Issue by khmarbaise** [jwiegley/svndumptool#11]
I'm using a dump file which contains at the beginning:

```
I have a dump file which contains the following at the beginning:
```

SVN-fs-dump-format-version: 2

UUID: 951035c1-ee3b-204b-9e9b-e186ef0bcd7f

Revision-number: 0
Prop-content-length: 56
Content-length: 56

K 8
svn:date
V 27
2014-06-04T13:37:22.270311Z
PROPS-END

Revision-number: 1
Prop-content-length: 101
Content-length: 101

K 10
svn:author
V 7
1234567
K 8
svn:date
V 27
2014-06-05T13:07:58.383299Z
K 7
svn:log
V 0

PROPS-END

Node-path: branches
Node-kind: dir
Node-action: add
Prop-content-length: 10
Content-length: 10

PROPS-END

Revision-number: 2
Prop-content-length: 101
Content-length: 101

K 10
svn:author
V 7
1234567
K 8
svn:date
V 27
2014-06-05T13:08:12.368927Z
K 7
svn:log
V 0

PROPS-END

Node-path: branches/4.1
Node-kind: dir
Node-action: add
Node-copyfrom-rev: 1
Node-copyfrom-path:

Revision-number: 3
Prop-content-length: 101
Content-length: 101

K 10
svn:author
V 7
1234567
K 8
svn:date
V 27
2014-06-05T13:08:51.138025Z
K 7
svn:log
V 0

PROPS-END

Node-path: branches/4.1/branches
Node-action: delete

```
Now I do a 
```

svndumptool.py merge original.dump \
  -r trunk migration/trunk \
  -r branches migration/branches \
  -r tags migration/tags \
  -o result.dump -d migration

```
Than the above entries:
```

Node-copyfrom-rev: 1
Node-copyfrom-path:

```
are no longer part of the resulting dump file but only for the revision 2. It seemed that only in the case for revision 2 this only happens but not for the other props....
```

**Comment by jwiegley** [comment]
Hi @khmarbaise , this repository is just a memory for `svndumptool`, but I'm not maintaining it.
